rzeczownik(samochod).
rzeczownik(dom).
rzeczownik(drzewo).
rzeczownik(czas).
rzeczownik(reka).
rzeczownik(miasto).
rzeczownik(ksiazka).
rzeczownik(dziecko).
rzeczownik(praca).
rzeczownik(kawa).
rzeczownik(kobieta).
rzeczownik(mezczyzna).
rzeczownik(szkola).
rzeczownik(zdrowie).
rzeczownik(pieniadze).
rzeczownik(telefon).
rzeczownik(jedzenie).
rzeczownik(pies).
rzeczownik(kot).
rzeczownik(film).
rzeczownik(muzyka).
rzeczownik(milosc).
rzeczownik(planeta).
rzeczownik(woda).
rzeczownik(powietrze).
rzeczownik(slonce).
rzeczownik(ksiezyc).
rzeczownik(obiad).
rzeczownik(sniadanie).
rzeczownik(samolot).
rzeczownik(prad).
rzeczownik(prysznic).
rzeczownik(drzwi).
rzeczownik(okno).
rzeczownik(kwiat).
rzeczownik(telewizja).
rzeczownik(komputer).
rzeczownik(buty).
rzeczownik(podroz).
rzeczownik(ruch).
rzeczownik(jablko).
rzeczownik(gitara).
rzeczownik(prad).
rzeczownik(rzeka).
rzeczownik(ocean).
rzeczownik(gora).
rzeczownik(deszcz).
rzeczownik(snieg).
rzeczownik(lato).
rzeczownik(zima).

czasownik(jest).
czasownik(ma).
czasownik(robi).
czasownik(powiedziec).
czasownik(chce).
czasownik(isc).
czasownik(widziec).
czasownik(myslec).
czasownik(mowic).
czasownik(zrobic).
czasownik(wiedziec).
czasownik(moge).
czasownik(pojsc).
czasownik(dac).
czasownik(brac).
czasownik(musiec).
czasownik(stac_sie).
czasownik(kochac).
czasownik(moc).
czasownik(zaczynac).
czasownik(widzialem).
czasownik(znalezc).
czasownik(przysc).
czasownik(jest).
czasownik(stawac_sie).
czasownik(pytac).
czasownik(znac).
czasownik(lubic).
czasownik(widziec).
czasownik(robi).
czasownik(pracowac).
czasownik(pomagac).
czasownik(zrobic).
czasownik(dzialac).
czasownik(trzymac).
czasownik(mowic).
czasownik(pomyslec).
czasownik(wyjsc).
czasownik(czekac).
czasownik(zamknac).
czasownik(sluchac).
czasownik(odpowiadac).
czasownik(zaczynac).
czasownik(pokazac).
czasownik(czuc).
czasownik(podrozowac).
czasownik(zrozumiec).
czasownik(spotykac).
czasownik(otworzyc).
czasownik(pamietac).


przymiotnik(duzy).
przymiotnik(maly).
przymiotnik(nowy).
przymiotnik(stary).
przymiotnik(dlugi).
przymiotnik(krotki).
przymiotnik(szybki).
przymiotnik(wolny).
przymiotnik(dobry).
przymiotnik(zly).
przymiotnik(ladny).
przymiotnik(brzydki).
przymiotnik(tani).
przymiotnik(drogi).
przymiotnik(bogaty).
przymiotnik(biedny).
przymiotnik(mlody).
przymiotnik(stary).
przymiotnik(zdrowy).
przymiotnik(chory).
przymiotnik(czysty).
przymiotnik(brudny).
przymiotnik(jasny).
przymiotnik(ciemny).
przymiotnik(cieply).
przymiotnik(zimny).
przymiotnik(sloneczny).
przymiotnik(mrozny).
przymiotnik(zadowolony).
przymiotnik(niezadowolony).
przymiotnik(smutny).
przymiotnik(wesoly).
przymiotnik(zwinny).
przymiotnik(niezreczny).
przymiotnik(smieszny).
przymiotnik(powazny).
przymiotnik(silny).
przymiotnik(slaby).
przymiotnik(spokojny).
przymiotnik(nerwowy).
przymiotnik(przyjazny).
przymiotnik(wrogi).
przymiotnik(bardzo).
przymiotnik(tylko).
przymiotnik(caly).
przymiotnik(szczesliwy).
przymiotnik(niezalezny).
przymiotnik(wspolczesny).

zadanie2(X,Y,Z):-

rzeczownik(X),

(czasownik(Y)),

((rzeczownik(Z));
(czasownik(Z)),
(przymiotnik(Z))
),

write("zdanie jest poprawne");
write("zdanie nie jest prawidlowe").

sprawdz(A,B,C,D,E):-
rzeczownik(A),

czasownik(B),

przymiotnik(C),

((rzeczownik(D));
(czasownik(D));
(przymiotnik(D))),

((rzeczownik(E));
(czasownik(E));
(przymiotnik(E))),
write("zdanie jest poprawne");
write("zdanie nie jest prawidlowe").